# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VoiceCommand

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ASRCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ASRCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsASRCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ASRCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x61\x73\x72\x32", size_prefixed=size_prefixed)

    # ASRCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ASRCommand
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ASRCommand
    def CommandType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ASRCommand
    def Command(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def Start(builder): builder.StartObject(3)
def ASRCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def ASRCommandAddName(builder, name):
    """This method is deprecated. Please switch to AddName."""
    return AddName(builder, name)
def AddCommandType(builder, commandType): builder.PrependUint8Slot(1, commandType, 0)
def ASRCommandAddCommandType(builder, commandType):
    """This method is deprecated. Please switch to AddCommandType."""
    return AddCommandType(builder, commandType)
def AddCommand(builder, command): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(command), 0)
def ASRCommandAddCommand(builder, command):
    """This method is deprecated. Please switch to AddCommand."""
    return AddCommand(builder, command)
def End(builder): return builder.EndObject()
def ASRCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)