# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VoiceCommand

class UnionCommand(object):
    NONE = 0
    VoiceSystemCommand = 1
    VoiceOperationCommand = 2
    VoiceNodeCommand = 3
    VoiceMapCommand = 4

