# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VoiceCommand

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceOperationCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceOperationCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceOperationCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VoiceOperationCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x61\x73\x72\x32", size_prefixed=size_prefixed)

    # VoiceOperationCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceOperationCommand
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VoiceOperationCommand
    def Time(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VoiceOperationCommand
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VoiceOperationCommand
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def VoiceOperationCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def VoiceOperationCommandAddObject(builder, object):
    """This method is deprecated. Please switch to AddObject."""
    return AddObject(builder, object)
def AddTime(builder, time): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(time), 0)
def VoiceOperationCommandAddTime(builder, time):
    """This method is deprecated. Please switch to AddTime."""
    return AddTime(builder, time)
def AddLocation(builder, location): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def VoiceOperationCommandAddLocation(builder, location):
    """This method is deprecated. Please switch to AddLocation."""
    return AddLocation(builder, location)
def AddAction(builder, action): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(action), 0)
def VoiceOperationCommandAddAction(builder, action):
    """This method is deprecated. Please switch to AddAction."""
    return AddAction(builder, action)
def End(builder): return builder.EndObject()
def VoiceOperationCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)