# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VoiceCommand

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceNodeCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceNodeCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceNodeCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VoiceNodeCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x61\x73\x72\x32", size_prefixed=size_prefixed)

    # VoiceNodeCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceNodeCommand
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 2

    # VoiceNodeCommand
    def NodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VoiceNodeCommand
    def FatherNodeId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VoiceNodeCommand
    def NodeName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(4)
def VoiceNodeCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddOp(builder, op): builder.PrependUint16Slot(0, op, 2)
def VoiceNodeCommandAddOp(builder, op):
    """This method is deprecated. Please switch to AddOp."""
    return AddOp(builder, op)
def AddNodeId(builder, nodeId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(nodeId), 0)
def VoiceNodeCommandAddNodeId(builder, nodeId):
    """This method is deprecated. Please switch to AddNodeId."""
    return AddNodeId(builder, nodeId)
def AddFatherNodeId(builder, fatherNodeId): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(fatherNodeId), 0)
def VoiceNodeCommandAddFatherNodeId(builder, fatherNodeId):
    """This method is deprecated. Please switch to AddFatherNodeId."""
    return AddFatherNodeId(builder, fatherNodeId)
def AddNodeName(builder, nodeName): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(nodeName), 0)
def VoiceNodeCommandAddNodeName(builder, nodeName):
    """This method is deprecated. Please switch to AddNodeName."""
    return AddNodeName(builder, nodeName)
def End(builder): return builder.EndObject()
def VoiceNodeCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)