# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VoiceCommand

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceSystemCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceSystemCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceSystemCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VoiceSystemCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x61\x73\x72\x32", size_prefixed=size_prefixed)

    # VoiceSystemCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceSystemCommand
    def Cmd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # VoiceSystemCommand
    def Param(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def Start(builder): builder.StartObject(2)
def VoiceSystemCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCmd(builder, cmd): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(cmd), 0)
def VoiceSystemCommandAddCmd(builder, cmd):
    """This method is deprecated. Please switch to AddCmd."""
    return AddCmd(builder, cmd)
def AddParam(builder, param): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(param), 0)
def VoiceSystemCommandAddParam(builder, param):
    """This method is deprecated. Please switch to AddParam."""
    return AddParam(builder, param)
def End(builder): return builder.EndObject()
def VoiceSystemCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)