# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VoiceCommand

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VoiceMapCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VoiceMapCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVoiceMapCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def VoiceMapCommandBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x61\x73\x72\x32", size_prefixed=size_prefixed)

    # VoiceMapCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VoiceMapCommand
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def Start(builder): builder.StartObject(1)
def VoiceMapCommandStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddOp(builder, op): builder.PrependUint16Slot(0, op, 0)
def VoiceMapCommandAddOp(builder, op):
    """This method is deprecated. Please switch to AddOp."""
    return AddOp(builder, op)
def End(builder): return builder.EndObject()
def VoiceMapCommandEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)